# Generated by Django 5.1.7 on 2025-04-15 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_cart_user_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySuppliments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categorySuppliments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.categorysuppliments')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='suppliments',
            field=models.ManyToManyField(related_name='products', to='market.suppliment'),
        ),
    ]
