# Generated by Django 5.1.7 on 2025-04-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='suppliments',
            field=models.ManyToManyField(blank=True, to='market.suppliment'),
        ),
    ]
