# Generated by Django 5.1.7 on 2025-04-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address'),
        ('market', '0005_remove_seller_created_at_remove_seller_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_stores',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='market.product'),
        ),
    ]
