# Generated by Django 5.1.7 on 2025-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_referral_code_customuser_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
    ]
